# Default configuration for JupyterHub
# See https://zero-to-jupyterhub.readthedocs.io/en/latest/resources/reference.html for all options

hub:
  config:
    Authenticator:
      admin_users:
        - admin
    JupyterHub:
      authenticator_class: dummy

proxy:
  secretToken: "replace-with-your-token" # Generate with: openssl rand -hex 32

singleuser:
  image:
    name: jupyter/minimal-notebook
    tag: latest
