apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

namespace: jupyterhub-staging

patches:
  - path: values-patch.yaml
    target:
      kind: HelmChart
      name: jupyterhub

helmCharts:
  - name: jupyterhub
    repo: https://hub.jupyter.org/helm-chart/
    version: 4.1.0
    releaseName: jupyterhub
    namespace: jupyterhub-staging
    valuesFile: values.yaml
