hub:
  config:
    Authenticator:
      admin_users:
        - admin
        - dev-user
    JupyterHub:
      authenticator_class: dummy
      admin_access: true

singleuser:
  image:
    name: jupyter/minimal-notebook
    tag: latest
  
  storage:
    type: none

  resources:
    requests:
      cpu: 0.2
      memory: 512Mi
    limits:
      cpu: 1
      memory: 1Gi

proxy:
  service:
    type: ClusterIP
  secretToken: "replace-with-your-dev-token" # Generate with: openssl rand -hex 32
