apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: example-app-prod
namePrefix: prd-

resources:
  - ../../base
  - namespace.yaml

patchesStrategicMerge:
  - deployment-patch.yaml
