apiVersion: kustomize.config.k8s.io/v1beta1
kind: HelmChartMetadata
metadata:
  name: jupyterhub
valuesInline:
  hub:
    config:
      JupyterHub:
        admin_access: false
    replicas: 2
  
  proxy:
    service:
      type: LoadBalancer
    https:
      enabled: true
      
  singleuser:
    storage:
      type: dynamic
      capacity: 1Gi
    
    resources:
      limits:
        cpu: 2
        memory: 4G
      requests:
        cpu: 0.1
        memory: 256M
