apiVersion: apps/v1
kind: Deployment
metadata:
  name: example-app
spec:
  replicas: 2
  template:
    spec:
      containers:
      - name: example-app
        image: nginx:stable
        env:
        - name: ENVIRONMENT
          value: staging
        resources:
          requests:
            cpu: 200m
            memory: 256Mi
          limits:
            cpu: 500m
            memory: 512Mi
