apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: jupyterhub-staging
namePrefix: stg-

resources:
  - ../../base
  - namespace.yaml

helmCharts:
- name: jupyterhub
  repo: https://hub.jupyter.org/helm-chart/
  version: 4.1.0
  releaseName: jupyterhub
  namespace: jupyterhub-staging
  valuesFile: ../../../../chart-values/staging-values.yaml
