hub:
  config:
    Authenticator:
      admin_users:
        - admin
    JupyterHub:
      authenticator_class: dummy
      admin_access: true

singleuser:
  image:
    name: jupyter/minimal-notebook
    tag: latest
  
  storage:
    type: none

proxy:
  service:
    type: ClusterIP
