hub:
  config:
    Authenticator:
      admin_users:
        - admin
    JupyterHub:
      authenticator_class: native
      admin_access: false
  
  replicas: 2

singleuser:
  image:
    name: jupyter/datascience-notebook
    tag: latest
  
  storage:
    type: dynamic
    capacity: 1Gi
  
  resources:
    limits:
      cpu: 2
      memory: 4G
    requests:
      cpu: 0.1
      memory: 256M

proxy:
  https:
    enabled: true
  service:
    type: LoadBalancer
