hub:
  config:
    Authenticator:
      admin_users:
        - admin
    JupyterHub:
      authenticator_class: dummy
      admin_access: true

singleuser:
  image:
    name: jupyter/datascience-notebook
    tag: latest
  
  storage:
    type: dynamic
    capacity: 1Gi

proxy:
  service:
    type: LoadBalancer
