apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml

helmCharts:
  - name: jupyterhub
    repo: https://jupyterhub.github.io/helm-chart/
    version: 2.0.0
    releaseName: jupyterhub
    namespace: jupyterhub
    valuesFile: values.yaml
