apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: example-app-appset
  namespace: argocd
spec:
  generators:
  - list:
      elements:
      - cluster: dev
        url: https://kubernetes.default.svc
        environment: dev
      - cluster: stg
        url: https://stg-cluster-url.example.com
        environment: staging
      - cluster: prd
        url: https://prd-cluster-url.example.com
        environment: prod
  template:
    metadata:
      name: example-app-{{cluster}}
    spec:
      project: default
      source:
        repoURL: https://github.com/vvcb/argocd-jupyterhub.git
        targetRevision: HEAD
        path: apps/example-app/overlays/{{environment}}
      destination:
        server: '{{url}}'
        namespace: example-app-{{environment}}
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
