apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: jupyterhub-appset
  namespace: argocd
spec:
  generators:
  - git:
      repoURL: https://github.com/vvcb/argocd-tre.git
      revision: HEAD
      files:
      - path: "clusters/clusters.yaml"
      template:
        apiVersion: argoproj.io/v1alpha1
        kind: ApplicationSet
        metadata:
          name: '{{name}}'
        spec:
          generators:
          - matrix:
              generators:
              - git:
                  repoURL: https://github.com/vvcb/argocd-tre.git
                  revision: HEAD
                  files:
                  - path: clusters/clusters.yaml
  template:
    metadata:
      name: jupyterhub-{{name}}
      labels:
        environment: {{environment}}
        {{range $key, $value := labels}}
        {{$key}}: {{$value}}
        {{end}}
    spec:
      project: default
      source:
        repoURL: https://github.com/vvcb/argocd-tre.git
        targetRevision: HEAD
        path: apps/jupyterhub/overlays/{{environment}}
      destination:
        server: '{{url}}'
        namespace: jupyterhub-{{environment}}
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
      ignoreDifferences:
      - group: "*"
        kind: "Secret"
        jsonPointers:
        - /data/proxy_token
        - /data/secret_token
